if [[ "$(hostname)" == "ernelson-mac" ]]; then
  export SYNC_ROOT="/Users/ernelson/Sync"
  export SYNC_DOCS="$SYNC_ROOT/Documents"
  alias xclipc="pbcopy"
else
  export SYNC_ROOT="/home/ernelson/Sync"
  export SYNC_DOCS="$HOME/Documents"
fi
export SYNC_WORK="$SYNC_DOCS/work"

# Filesystem
alias legion="cd $NSK_GIT_DIR/legion"

# Cmd
# completion
alias gencompletion="kubectl completion zsh > $DOTFILES_DIR/kubectl_completion.sh && oc completion zsh > ~/.dotfiles/oc_completion.sh"
alias ocompl="source $DOTFILES_DIR/oc_completion.sh"
alias kcompl="source $DOTFILES_DIR/kubectl_completion.sh"

#alias podman="docker"
alias pd="podman"
alias fw='sudo firewall-cmd'
alias fwp='sudo firewall-cmd --permanent'
alias tmux="tmux -2"
alias dirsize="du -sh"
alias riftup="wg-quick up wg0-rift"
alias riftdown="wg-quick down wg0-rift"
alias sshrig="ssh -A nskd.usersys.redhat.com"
alias sshb="ssh -A baldur"
alias moshb='mosh --ssh="ssh -A" baldur'
alias ssha="ssh -A tundra"
alias ig="grep -i"
alias ifi="find . -iname"
alias loadz="source ~/.zshrc"
alias s="ag"
alias si="ag -i"
alias k="kubectl"
alias kx="kubectx"
alias kz="kustomize"
alias kn="kubens"
alias mk="minikube"
alias ic="istioctl"
alias kb="kubebuilder"
alias osdk="operator-sdk"
alias o="oc"
alias ipb="ip -br -color"
alias ap="ansible-playbook"
alias kp="kubectl get pods --all-namespaces"
alias kpw="watch 'kubectl get pods --all-namespaces'"
alias uuid="uuidgen | tr -d - | tr -d '\n' | tr '[:upper:]' '[:lower:]'"
alias externalip="curl ipinfo.io/ip"
alias lt="ls -ltah"
alias m="make"
alias mr="make run"
alias mt="make test"
alias mb="make build"
alias threedisplay="$HOME/.screenlayout/three-display.sh"
alias watchicsp="watch 'oc describe node -l node-role.kubernetes.io/worker= | grep -e Name: -e rendered'"
alias dumpcors="oc get -n openshift-migration route/migration -o go-template='(?i)//{{ .spec.host }}(:|\z){{ println }}' | sed 's,\.,\\.,g'"
alias jj="jekyll"
alias nskencrypt='gpg2 -e -r "Erik Nelson <erik@nsk.io>"'
alias nskdecrypt='gpg2'

# git cmd, NOTE: a bunch of aliases are brought in via OMZSH
alias g="git"
alias lg="lazygit"
alias fetch="git fetch --all && git fetch --all --tags"
alias gitsync="git fetch --all && git merge upstream/master && git push origin"
#alias com="git commit -S"
alias com="git commit"
#alias amend="git commit -S --amend"
alias amend="git commit --amend"
alias push="git push"
alias pull="git pull"
alias reset="git reset"
alias gd="git diff"
alias gds="git diff --staged"
alias add="git add"
alias goa='git log --pretty=format:"%h%x09%an%x09%ad%x09%s"'

# Arch cmd
alias paci="sudo pacmatic -S"
alias pacr="sudo pacmatic -Rns"
alias pacu="sudo pacmatic -Syyu"
alias pacs="pacmatic -Ss"
alias pacinstalled="pacmatic -Qe"
alias pacwhy="pacman -Qi"
alias pacfiles="pacmatic -Ql"
alias pacinfo="pacmatic -Si"
alias aur="auracle"

# Filesystem jumps
alias gg="cd $NSK_GIT_DIR"
alias gopath="cd $GOPATH"
alias dotfiles="cd $DOTFILES_DIR"
alias sff="cd $NSK_GIT_DIR/stuff"
alias cds="cd $SYNC_ROOT"
alias cdw="cd $SYNC_WORK"
alias fum="cd $NSK_GIT_DIR/fumar"
alias blog="cd $NSK_GIT_DIR/kcac.nsk.io"

# mig filesystem jumps
alias ch="cd $NSK_GIT_DIR/crane-handbook"
alias cr="cd $GOPATH/src/github.com/konveyor/crane"
alias crn="cd $NSK_GIT_DIR/crane-runner"
alias mig="cd $NSK_GIT_DIR/mig"
alias migd="cd $NSK_GIT_DIR/mig/mig-dev"
alias migci="cd $NSK_GIT_DIR/mig/mig-ci"
alias migen="cd $NSK_GIT_DIR/mig/konveyor-enhancements"
alias migcom="cd $NSK_GIT_DIR/konveyor-community"
alias mm="cd $NSK_GIT_DIR/mig/mig-ui"
alias kgi="cd $NSK_GIT_DIR/konveyor.github.io"
alias ww="cd $NSK_GIT_DIR/wadsworth"
alias migop="cd $NSK_GIT_DIR/mig/mig-operator"
alias migbp="cd $NSK_GIT_DIR/mig/openshift-migration-best-practices"
alias migdown="cd $NSK_GIT_DIR/mig/downstream"
alias agd="cd $NSK_GIT_DIR/mig/mig-agnosticd"
alias cpma="cd $GOPATH/src/github.com/konveyor/cpma"
alias migc="cd $GOPATH/src/github.com/konveyor/mig-controller"
alias rhblog="$NSK_GIT_DIR/mig/rh-blogs"

# Edit shortcuts
alias editi="vim ~/.i3/config"
alias editb="vim ~/.bashrc"
alias editbp="vim ~/.bash_profile"
alias editz="vim ~/.zshrc"
alias editze="vim ~/.zshenv"
alias editv="vim ~/.vimrc"
alias editt="vim $SYNC_DOCS/todo.txt"
alias editpt="vim $SYNC_DOCS/ptodo.txt"
