#!/bin/bash
_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
aur_dir=~/aur
readarray -t pkg_arr < <( \
  cd $aur_dir && \
  /usr/bin/auracle update | perl -ne '/update complete: (\/.*$)/ && print "$1\n"'
)

for pkg_path in "${pkg_arr[@]}"; do
  cd $pkg_path
  makepkg -si
done
